name: Deploy FastAPI to EC2 (systemd, no TLS)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Assignments/Session2-23Aug2025/clinicalbert-api/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (for $GITHUB_REPOSITORY info)
        uses: actions/checkout@v4

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      - name: Remote deploy (systemd + nginx)
        env:
          EC2_HOST:           ${{ secrets.EC2_HOST }}
          EC2_USER:           ${{ vars.EC2_USER || 'ubuntu' }}
          EC2_APP_DIR:        ${{ secrets.EC2_APP_DIR }}   # e.g. /home/ubuntu/apps/clinicalbert
          APP_SUBDIR:         Assignments/Session2-23Aug2025/clinicalbert-api
          BRANCH:             ${{ vars.DEPLOY_BRANCH || 'main' }}
          GITHUB_REPOSITORY:  ${{ github.repository }}
          ENTRY:              main:app                     # use app.main:app if your app is in app/main.py
        run: |
          # Pass env to remote and run script
          ssh -o StrictHostKeyChecking=no "${EC2_USER}@${EC2_HOST}" \
            "EC2_APP_DIR='${EC2_APP_DIR}' APP_SUBDIR='${APP_SUBDIR}' BRANCH='${BRANCH}' GITHUB_REPOSITORY='${GITHUB_REPOSITORY}' ENTRY='${ENTRY}' bash -s" <<'EOF'
          set -euxo pipefail

          sudo apt-get update -y
          sudo apt-get install -y python3-pip python3-venv git nginx

          mkdir -p "${EC2_APP_DIR}"
          cd "${EC2_APP_DIR}"

          if [ -d .git ]; then
            git fetch --all
            git reset --hard "origin/${BRANCH}"
          else
            git init
            git remote add origin "https://github.com/${GITHUB_REPOSITORY}.git"
            git fetch origin "${BRANCH}"
            git checkout -b "${BRANCH}" FETCH_HEAD
          fi

          APP_PATH="${EC2_APP_DIR}/${APP_SUBDIR}"

          # venv + deps
          python3 -m venv "${APP_PATH}/.venv"
          . "${APP_PATH}/.venv/bin/activate"
          python -m pip install --upgrade pip wheel
          if [ -f "${APP_PATH}/requirements.txt" ]; then
            pip install -r "${APP_PATH}/requirements.txt"
          else
            pip install "${APP_PATH}"
          fi

          # systemd unit (service name: fastapi)
          sudo tee /etc/systemd/system/fastapi.service >/dev/null <<UNIT
          [Unit]
          Description=FastAPI (Uvicorn) - clinicalbert-api
          After=network.target

          [Service]
          User=${USER}
          WorkingDirectory=${APP_PATH}
          Environment="PATH=${APP_PATH}/.venv/bin"
          EnvironmentFile=-${APP_PATH}/.env
          ExecStart=${APP_PATH}/.venv/bin/uvicorn ${ENTRY} --host 127.0.0.1 --port 8001 --workers 2
          Restart=always
          RestartSec=5

          [Install]
          WantedBy=multi-user.target
          UNIT

          sudo systemctl daemon-reload
          sudo systemctl enable fastapi || true
          sudo systemctl restart fastapi

          # nginx site → proxy to localhost:8001
          sudo tee /etc/nginx/sites-available/fastapi >/dev/null <<'NGINX'
          server {
            listen 80;
            server_name _;
            location /                  { proxy_pass http://127.0.0.1:8001; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto $scheme; }
            location /docs              { proxy_pass http://127.0.0.1:8001; }
            location /openapi.json      { proxy_pass http://127.0.0.1:8001; }
            location /health            { proxy_pass http://127.0.0.1:8001; access_log off; }
          }
          NGINX
          sudo ln -sf /etc/nginx/sites-available/fastapi /etc/nginx/sites-enabled/fastapi
          sudo rm -f /etc/nginx/sites-enabled/default || true
          sudo nginx -t
          sudo systemctl restart nginx

          # quick local checks (don't fail job)
          curl -fsS http://127.0.0.1:8001/openapi.json >/dev/null && echo "Uvicorn OK" || true
          curl -fsS http://localhost/docs >/dev/null && echo "/docs OK via nginx" || true
          EOF
      - name: Smoke test (external)
        env:
          URL: ${{ format('http://{0}/docs', secrets.EC2_HOST) }}
        run: |
          for i in {1..30}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
            if [ "$code" -ge 200 ] && [ "$code" -lt 400 ]; then
              echo "### Deployment OK" >> $GITHUB_STEP_SUMMARY
              echo "- /docs reachable" >> $GITHUB_STEP_SUMMARY
              exit 0
            fi
            sleep 2
          done
          exit 1      
